const initialCards = [
  {
    id: "801",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Arabescato",
    interiors: [
      require("../images/catalog/GK_Elite/Arabescato/interiors/Arabescato-v-interere-1.jpg"),
      require("../images/catalog/GK_Elite/Arabescato/interiors/Arabescato-v-interere-2.jpg"),
      require("../images/catalog/GK_Elite/Arabescato/interiors/Arabescato-v-interere-3.jpg"),
      require("../images/catalog/GK_Elite/Arabescato/interiors/Arabescato-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Arabescato/tovars/Arabescato.jpg"),
      require("../images/catalog/GK_Elite/Arabescato/tovars/variant-razmeshcheniya(27).jpg"),
    ],
  },
  {
    id: "802",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Arabescato Orobico",
    interiors: [
      require("../images/catalog/GK_Elite/Arabescato Orobico/interiors/Arabescato-Orobico v-interere-2.jpg"),
      require("../images/catalog/GK_Elite/Arabescato Orobico/interiors/Arabescato-Orobico v-interere-3.jpg"),
      require("../images/catalog/GK_Elite/Arabescato Orobico/interiors/Arabescato-Orobico v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Arabescato Orobico/tovars/Arabescato-Orobico(1).jpg"),
      require("../images/catalog/GK_Elite/Arabescato Orobico/tovars/variant-razmeshcheniya(42).jpg"),
    ],
  },
  {
    id: "803",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Azul Ceilo",
    interiors: [
      require("../images/catalog/GK_Elite/Azul Ceilo/interiors/Azul-Ceilo-v-interere-1.png"),
      require("../images/catalog/GK_Elite/Azul Ceilo/interiors/Azul-Ceilo-v-interere-2.png"),
      require("../images/catalog/GK_Elite/Azul Ceilo/interiors/Azul-Ceilo-v-interere-3.png"),
      require("../images/catalog/GK_Elite/Azul Ceilo/interiors/Azul-Ceilo-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Azul Ceilo/tovars/Azul-Ceilo-v-interere.png"),
      require("../images/catalog/GK_Elite/Azul Ceilo/tovars/variant-razmeshcheniya.png"),
    ],
  },
  {
    id: "804",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Bianca Carrara",
    interiors: [
      require("../images/catalog/GK_Elite/Bianca Carrara/interiors/Bianca-Carrara-v-interere-1.jpg"),
      require("../images/catalog/GK_Elite/Bianca Carrara/interiors/Bianca-Carrara-v-interere-2.jpg"),
      require("../images/catalog/GK_Elite/Bianca Carrara/interiors/Bianca-Carrara-v-interere-3.jpg"),
      require("../images/catalog/GK_Elite/Bianca Carrara/interiors/Bianca-Carrara-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Bianca Carrara/tovars/Bianca-Carrara.jpg"),
      require("../images/catalog/GK_Elite/Bianca Carrara/tovars/variant-razmeshcheniya(28).jpg"),
    ],
  },
  {
    id: "805",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Bianco Statuario",
    interiors: [
      require("../images/catalog/GK_Elite/Bianco Statuario/interiors/Bianco-Statuario-v-interrere-1.png"),
      require("../images/catalog/GK_Elite/Bianco Statuario/interiors/Bianco-Statuario-v-interrere-2.png"),
      require("../images/catalog/GK_Elite/Bianco Statuario/interiors/Bianco-Statuario-v-interrere-3.png"),
      require("../images/catalog/GK_Elite/Bianco Statuario/interiors/Bianco-Statuario-v-interrere-4.png"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Bianco Statuario/tovars/Bianco-Statuario.png"),
      require("../images/catalog/GK_Elite/Bianco Statuario/tovars/variant-razmeshcheniya(1).png"),
    ],
  },
  {
    id: "806",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Bidasar Gold",
    interiors: [
      require("../images/catalog/GK_Elite/Bidasar Gold/interiors/Bidasar-Gold-v-interere-1.jpg"),
      require("../images/catalog/GK_Elite/Bidasar Gold/interiors/Bidasar-Gold-v-interere-2.jpg"),
      require("../images/catalog/GK_Elite/Bidasar Gold/interiors/Bidasar-Gold-v-interere-3.jpg"),
      require("../images/catalog/GK_Elite/Bidasar Gold/interiors/Bidasar-Gold-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Bidasar Gold/tovars/Bidasar-Gold.jpg"),
      require("../images/catalog/GK_Elite/Bidasar Gold/tovars/variant-razmeshcheniya(29).jpg"),
    ],
  },
  {
    id: "807",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Bleu Fleuri",
    interiors: [
      require("../images/catalog/GK_Elite/Bleu Fleuri/interiors/Bleu-Fleuri-v-interere-1.jpg"),
      require("../images/catalog/GK_Elite/Bleu Fleuri/interiors/Bleu-Fleuri-v-interere-2.jpg"),
      require("../images/catalog/GK_Elite/Bleu Fleuri/interiors/Bleu-Fleuri-v-interere-3(1).jpg"),
      require("../images/catalog/GK_Elite/Bleu Fleuri/interiors/Bleu-Fleuri-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Bleu Fleuri/tovars/Bleu-Fleuri.jpg"),
      require("../images/catalog/GK_Elite/Bleu Fleuri/tovars/variant-razmeshcheniya(30).jpg"),
    ],
  },
  {
    id: "808",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Blue Cappella",
    interiors: [
      require("../images/catalog/GK_Elite/Blue Cappella/interiors/Blue-Cappella-v-interere-1.png"),
      require("../images/catalog/GK_Elite/Blue Cappella/interiors/Blue-Cappella-v-interere-2.png"),
      require("../images/catalog/GK_Elite/Blue Cappella/interiors/Blue-Cappella-v-interere-3.png"),
      require("../images/catalog/GK_Elite/Blue Cappella/interiors/Blue-Cappella-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Blue Cappella/tovars/Blue-Cappella.png"),
      require("../images/catalog/GK_Elite/Blue Cappella/tovars/variant-razmeshcheniya(5).png"),
    ],
  },
  {
    id: "809",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Blue Turquin",
    interiors: [
      require("../images/catalog/GK_Elite/Blue Turquin/interiors/Blue-Turquin-v-interere-1.jpg"),
      require("../images/catalog/GK_Elite/Blue Turquin/interiors/Blue-Turquin-v-interere-2.jpg"),
      require("../images/catalog/GK_Elite/Blue Turquin/interiors/Blue-Turquin-v-interere-3.jpg"),
      require("../images/catalog/GK_Elite/Blue Turquin/interiors/Blue-Turquin-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Blue Turquin/tovars/Blue-Turquin.jpg"),
      require("../images/catalog/GK_Elite/Blue Turquin/tovars/variant-razmeshcheniya(31).jpg"),
    ],
  },
  {
    id: "810",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Breccia Damascata",
    interiors: [
      require("../images/catalog/GK_Elite/Breccia Damascata/interiors/Breccia-Damascata-v-interere-1.png"),
      require("../images/catalog/GK_Elite/Breccia Damascata/interiors/Breccia-Damascata-v-interere-2.png"),
      require("../images/catalog/GK_Elite/Breccia Damascata/interiors/Breccia-Damascata-v-interere-3.png"),
      require("../images/catalog/GK_Elite/Breccia Damascata/interiors/Breccia-Damascata-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Breccia Damascata/tovars/Breccia-Damascata.png"),
      require("../images/catalog/GK_Elite/Breccia Damascata/tovars/variant-razmeshcheniya(4).png"),
    ],
  },
  {
    id: "811",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Calcite Blue",
    interiors: [
      require("../images/catalog/GK_Elite/Calcite Blue/interiors/Calcite-Blue-v-interere-1 (1).png"),
      require("../images/catalog/GK_Elite/Calcite Blue/interiors/Calcite-Blue-v-interere-2.png"),
      require("../images/catalog/GK_Elite/Calcite Blue/interiors/Calcite-Blue-v-interere-3.png"),
      require("../images/catalog/GK_Elite/ Calcite Blue/interiors/Calcite-Blue-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Calcite Blue/tovars/Calcite-Blue.png"),
      require("../images/catalog/GK_Elite/Calcite Blue/tovars/variant-razmeshcheniya(9).png"),
    ],
  },
  {
    id: "812",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Daino Reale",
    interiors: [
      require("../images/catalog/GK_Elite/Daino Reale/interiors/Daino-Reale-v-interere-1.png"),
      require("../images/catalog/GK_Elite/Daino Reale/interiors/Daino-Reale-v-interere-2.png"),
      require("../images/catalog/GK_Elite/Daino Reale/interiors/Daino-Reale-v-interere-3.png"),
      require("../images/catalog/GK_Elite/Daino Reale/interiors/Daino-Reale-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Daino Reale/tovars/Calcite-Blue-v-interere-1.png"),
      require("../images/catalog/GK_Elite/Daino Reale/tovars/Daino-Reale.png"),
      require("../images/catalog/GK_Elite/Daino Reale/tovars/variant-razmeshcheniya(8).png"),
    ],
  },
  {
    id: "813",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Diablo",
    interiors: [
      require("../images/catalog/GK_Elite/Diablo/interiors/Diablo-v-interere-1.jpg"),
      require("../images/catalog/GK_Elite/Diablo/interiors/Diablo-v-interere-2.jpg"),
      require("../images/catalog/GK_Elite/Diablo/interiors/Diablo-v-interere-3.jpg"),
      require("../images/catalog/GK_Elite/Diablo/interiors/Diablo-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Diablo/tovars/Diablo.jpg"),
      require("../images/catalog/GK_Elite/Diablo/tovars/variant-razmeshcheniya(32).jpg"),
    ],
  },
  {
    id: "814",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Disette Basi",
    interiors: [
      require("../images/catalog/GK_Elite/Disette Basi/interiors/Disette-Basi-v-interere-1.jpg"),
      require("../images/catalog/GK_Elite/Disette Basi/interiors/Disette-Basi-v-interere-2.jpg"),
      require("../images/catalog/GK_Elite/Disette Basi/interiors/Disette-Basi-v-interere-3.jpg"),
      require("../images/catalog/GK_Elite/Disette Basi/interiors/Disette-Basi-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Disette Basi/tovars/Disette-Basi.jpg"),
      require("../images/catalog/GK_Elite/Disette Basi/tovars/variant-razmeshcheniya(33).jpg"),
    ],
  },
  {
    id: "815",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Dorato",
    interiors: [
      require("../images/catalog/GK_Elite/Dorato/interiors/Dorato-v-intereere-1.jpg"),
      require("../images/catalog/GK_Elite/Dorato/interiors/Dorato-v-intereere-2.jpg"),
      require("../images/catalog/GK_Elite/Dorato/interiors/Dorato-v-intereere-3.jpg"),
      require("../images/catalog/GK_Elite/Dorato/interiors/Dorato-v-intereere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Dorato/tovars/Dorato.jpg"),
      require("../images/catalog/GK_Elite/Dorato/tovars/variant-razmeshcheniya(34).jpg"),
    ],
  },
  {
    id: "816",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Michelangelo",
    interiors: [
      require("../images/catalog/GK_Elite/Michelangelo/interiors/Michelangelo-v-interere-1.jpg"),
      require("../images/catalog/GK_Elite/Michelangelo/interiors/Michelangelo-v-interere-2.jpg"),
      require("../images/catalog/GK_Elite/Michelangelo/interiors/Michelangelo-v-interere-3.jpg"),
      require("../images/catalog/GK_Elite/Michelangelo/interiors/Michelangelo-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Michelangelo/tovars/Michelangelo.jpg"),
      require("../images/catalog/GK_Elite/Michelangelo/tovars/variant-razmeshcheniya(35).jpg"),
    ],
  },
  {
    id: "817",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Nuvolato",
    interiors: [
      require("../images/catalog/GK_Elite/Nuvolato/interiors/Nuvolato-v-interere-1.jpg"),
      require("../images/catalog/GK_Elite/Nuvolato/interiors/Nuvolato-v-interere-2.jpg"),
      require("../images/catalog/GK_Elite/Nuvolato/interiors/Nuvolato-v-interere-3.jpg"),
      require("../images/catalog/GK_Elite/Nuvolato/interiors/Nuvolato-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Nuvolato/tovars/Nuvolato.jpg"),
      require("../images/catalog/GK_Elite/Nuvolato/tovars/variant-razmeshcheniya(36).jpg"),
    ],
  },
  {
    id: "818",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Palissandro Blue Ocean",
    interiors: [
      require("../images/catalog/GK_Elite/Palissandro Blue Ocean/interiors/Palissandro-Blue-Ocean-v-interere-1.png"),
      require("../images/catalog/GK_Elite/Palissandro Blue Ocean/interiors/Palissandro-Blue-Ocean-v-interere-2.png"),
      require("../images/catalog/GK_Elite/Palissandro Blue Ocean/interiors/Palissandro-Blue-Ocean-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Palissandro Blue Ocean/tovars/Palissandro-Blue-Ocean.png"),
      require("../images/catalog/GK_Elite/Palissandro Blue Ocean/tovars/variant-razmeshcheniya(7).png"),
    ],
  },
  {
    id: "819",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Pietra Stellaria",
    interiors: [
      require("../images/catalog/GK_Elite/Pietra Stellaria/interiors/Pietra-Stellaria-v-interere-1.jpg"),
      require("../images/catalog/GK_Elite/Pietra Stellaria/interiors/Pietra-Stellaria-v-interere-2.jpg"),
      require("../images/catalog/GK_Elite/Pietra Stellaria/interiors/Pietra-Stellaria-v-interere-3.jpg"),
      require("../images/catalog/GK_Elite/Pietra Stellaria/interiors/Pietra-Stellaria-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Pietra Stellaria/tovars/Pietra-Stellaria.jpg"),
      require("../images/catalog/GK_Elite/Pietra Stellaria/tovars/variant-razmeshcheniya(37).jpg"),
    ],
  },
  {
    id: "820",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Porto Santo",
    interiors: [
      require("../images/catalog/GK_Elite/Porto Santo/interiors/Porto-Santo-v-interere-1.jpg"),
      require("../images/catalog/GK_Elite/Porto Santo/interiors/Porto-Santo-v-interere-2.jpg"),
      require("../images/catalog/GK_Elite/Porto Santo/interiors/Porto-Santo-v-interere-3.jpg"),
      require("../images/catalog/GK_Elite/Porto Santo/interiors/Porto-Santo-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Porto Santo/tovars/Porto-Santo.jpg"),
      require("../images/catalog/GK_Elite/Porto Santo/tovars/variant-razmeshcheniya(38).jpg"),
    ],
  },
  {
    id: "821",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Rojo Alicante",
    interiors: [
      require("../images/catalog/GK_Elite/Rojo Alicante/interiors/Rojo-Alicante-v-interere-1.png"),
      require("../images/catalog/GK_Elite/Rojo Alicante/interiors/Rojo-Alicante-v-interere-2.png"),
      require("../images/catalog/GK_Elite/Rojo Alicante/interiors/Rojo-Alicante-v-interere-3.png"),
      require("../images/catalog/GK_Elite/Rojo Alicante/interiors/Rojo-Alicante-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Rojo Alicante/tovars/Rojo-Alicante.png"),
      require("../images/catalog/GK_Elite/Rojo Alicante/tovars/variant-razmeshcheniya(2).png"),
    ],
  },
  {
    id: "822",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Rosso Verona",
    interiors: [
      require("../images/catalog/GK_Elite/Rosso Verona/interiors/Rosso-Verona-v-interere-1.png"),
      require("../images/catalog/GK_Elite/Rosso Verona/interiors/Rosso-Verona-v-interere-2.png"),
      require("../images/catalog/GK_Elite/Rosso Verona/interiors/Rosso-Verona-v-interere-3.png"),
      require("../images/catalog/GK_Elite/Rosso Verona/interiors/Rosso-Verona-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Rosso Verona/tovars/Rosso-Verona.png"),
      require("../images/catalog/GK_Elite/Rosso Verona/tovars/variant-razmeshcheniya(3).png"),
    ],
  },
  {
    id: "823",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Sainte Anne",
    interiors: [
      require("../images/catalog/GK_Elite/Rosso Verona/interiors/Sainte-Anne-v-interere-1.jpg"),
      require("../images/catalog/GK_Elite/Rosso Verona/interiors/Sainte-Anne-v-interere-2.jpg"),
      require("../images/catalog/GK_Elite/Rosso Verona/interiors/Sainte-Anne-v-interere-3.jpg"),
      require("../images/catalog/GK_Elite/Rosso Verona/interiors/Sainte-Anne-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Rosso Verona/tovars/Sainte-Anne.jpg"),
      require("../images/catalog/GK_Elite/Rosso Verona/tovars/variant-razmeshcheniya(39).jpg"),
    ],
  },
  {
    id: "824",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Sandy Grey",
    interiors: [
      require("../images/catalog/GK_Elite/Sandy Grey/interiors/Sandy-Grey-v-interere-1.png"),
      require("../images/catalog/GK_Elite/Sandy Grey/interiors/Sandy-Grey-v-interere-2.png"),
      require("../images/catalog/GK_Elite/Sandy Grey/interiors/Sandy-Grey-v-interere-3.png"),
      require("../images/catalog/GK_Elite/Sandy Grey/interiors/Sandy-Grey-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Sandy Grey/tovars/Sandy-Grey.png"),
      require("../images/catalog/GK_Elite/Sandy Grey/tovars/variant-razmeshcheniya(6).png"),
    ],
  },
  {
    id: "825",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Tobaco",
    interiors: [
      require("../images/catalog/GK_Elite/Tobaco/interiors/Tobaco-v-interere-1.jpg"),
      require("../images/catalog/GK_Elite/Tobaco/interiors/Tobaco-v-interere-2.jpg"),
      require("../images/catalog/GK_Elite/Tobaco/interiors/Tobaco-v-interere-3.jpg"),
      require("../images/catalog/GK_Elite/Tobaco/interiors/Tobaco-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Tobaco/tovars/Tobaco.jpg"),
      require("../images/catalog/GK_Elite/Tobaco/tovars/variant-razmeshcheniya(40).jpg"),
    ],
  },
  {
    id: "826",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Verde Antico",
    interiors: [
      require("../images/catalog/GK_Elite/Verde Antico/interiors/Verde-Antico-v-interere-1.jpg"),
      require("../images/catalog/GK_Elite/Verde Antico/interiors/Verde-Antico-v-interere-2.jpg"),
      require("../images/catalog/GK_Elite/Verde Antico/interiors/Verde-Antico-v-interere-3.jpg"),
      require("../images/catalog/GK_Elite/Verde Antico/interiors/Verde-Antico-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_Elite/Verde Antico/tovars/variant-razmeshcheniya(41).jpg"),
      require("../images/catalog/GK_Elite/Verde Antico/tovars/Verde-Antico.jpg"),
    ],
  },
];
