const initialCards = [
  {
    id: "801",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Arabescato",
    interiors: [
      require("../images/catalog/Arabescato-v-interere-1.jpg"),
      require("../images/catalog/Arabescato-v-interere-2.jpg"),
      require("../images/catalog/Arabescato-v-interere-3.jpg"),
      require("../images/catalog/Arabescato-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/Arabescato.jpg"),
      require("../images/catalog/variant-razmeshcheniya(27).jpg"),
    ],
  },
  {
    id: "802",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Arabescato Orobico",
    interiors: [
      require("../images/catalog/Arabescato-Orobico v-interere-2.jpg"),
      require("../images/catalog/Arabescato-Orobico v-interere-3.jpg"),
      require("../images/catalog/Arabescato-Orobico v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/Arabescato-Orobico(1).jpg"),
      require("../images/catalog/variant-razmeshcheniya(42).jpg"),
    ],
  },
  {
    id: "803",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Azul Ceilo",
    interiors: [
      require("../images/catalog/Azul-Ceilo-v-interere-1.png"),
      require("../images/catalog/Azul-Ceilo-v-interere-2.png"),
      require("../images/catalog/Azul-Ceilo-v-interere-3.png"),
      require("../images/catalog/Azul-Ceilo-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/Azul-Ceilo-v-interere.png"),
      require("../images/catalog/variant-razmeshcheniya.png"),
    ],
  },
  {
    id: "804",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Bianca Carrara",
    interiors: [
      require("../images/catalog/Bianca-Carrara-v-interere-1.jpg"),
      require("../images/catalog/Bianca-Carrara-v-interere-2.jpg"),
      require("../images/catalog/Bianca-Carrara-v-interere-3.jpg"),
      require("../images/catalog/Bianca-Carrara-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/Bianca-Carrara.jpg"),
      require("../images/catalog/variant-razmeshcheniya(28).jpg"),
    ],
  },
  {
    id: "805",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Bianco Statuario",
    interiors: [
      require("../images/catalog/Bianco-Statuario-v-interrere-1.png"),
      require("../images/catalog/Bianco-Statuario-v-interrere-2.png"),
      require("../images/catalog/Bianco-Statuario-v-interrere-3.png"),
      require("../images/catalog/Bianco-Statuario-v-interrere-4.png"),
    ],
    tovars: [
      require("../images/catalog/Bianco-Statuario.png"),
      require("../images/catalog/variant-razmeshcheniya(1).png"),
    ],
  },
  {
    id: "806",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Bidasar Gold",
    interiors: [
      require("../images/catalog/Bidasar-Gold-v-interere-1.jpg"),
      require("../images/catalog/Bidasar-Gold-v-interere-2.jpg"),
      require("../images/catalog/Bidasar-Gold-v-interere-3.jpg"),
      require("../images/catalog/Bidasar-Gold-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/Bidasar-Gold.jpg"),
      require("../images/catalog/variant-razmeshcheniya(29).jpg"),
    ],
  },
  {
    id: "807",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Bleu Fleuri",
    interiors: [
      require("../images/catalog/Bleu-Fleuri-v-interere-1.jpg"),
      require("../images/catalog/Bleu-Fleuri-v-interere-2.jpg"),
      require("../images/catalog/Bleu-Fleuri-v-interere-3(1).jpg"),
      require("../images/catalog/Bleu-Fleuri-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/Bleu-Fleuri.jpg"),
      require("../images/catalog/variant-razmeshcheniya(30).jpg"),
    ],
  },
  {
    id: "808",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Blue Cappella",
    interiors: [
      require("../images/catalog/Blue-Cappella-v-interere-1.png"),
      require("../images/catalog/Blue-Cappella-v-interere-2.png"),
      require("../images/catalog/Blue-Cappella-v-interere-3.png"),
      require("../images/catalog/Blue-Cappella-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/Blue-Cappella.png"),
      require("../images/catalog/variant-razmeshcheniya(5).png"),
    ],
  },
  {
    id: "809",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Blue Turquin",
    interiors: [
      require("../images/catalog/Blue-Turquin-v-interere-1.jpg"),
      require("../images/catalog/Blue-Turquin-v-interere-2.jpg"),
      require("../images/catalog/Blue-Turquin-v-interere-3.jpg"),
      require("../images/catalog/Blue-Turquin-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/Blue-Turquin.jpg"),
      require("../images/catalog/variant-razmeshcheniya(31).jpg"),
    ],
  },
  {
    id: "810",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Breccia Damascata",
    interiors: [
      require("../images/catalog/Breccia-Damascata-v-interere-1.png"),
      require("../images/catalog/Breccia-Damascata-v-interere-2.png"),
      require("../images/catalog/Breccia-Damascata-v-interere-3.png"),
      require("../images/catalog/Breccia-Damascata-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/Breccia-Damascata.png"),
      require("../images/catalog/variant-razmeshcheniya(4).png"),
    ],
  },
  {
    id: "811",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Calcite Blue",
    interiors: [
      require("../images/catalog/Calcite-Blue-v-interere-1 (1).png"),
      require("../images/catalog/Calcite-Blue-v-interere-2.png"),
      require("../images/catalog/Calcite-Blue-v-interere-3.png"),
      require("../images/catalog/Calcite-Blue-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/Calcite-Blue.png"),
      require("../images/catalog/variant-razmeshcheniya(9).png"),
    ],
  },
  {
    id: "812",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Daino Reale",
    interiors: [
      require("../images/catalog/Daino-Reale-v-interere-1.png"),
      require("../images/catalog/Daino-Reale-v-interere-2.png"),
      require("../images/catalog/Daino-Reale-v-interere-3.png"),
      require("../images/catalog/Daino-Reale-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/Calcite-Blue-v-interere-1.png"),
      require("../images/catalog/Daino-Reale.png"),
      require("../images/catalog/variant-razmeshcheniya(8).png"),
    ],
  },
  {
    id: "813",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Diablo",
    interiors: [
      require("../images/catalog/Diablo-v-interere-1.jpg"),
      require("../images/catalog/Diablo-v-interere-2.jpg"),
      require("../images/catalog/Diablo-v-interere-3.jpg"),
      require("../images/catalog/Diablo-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/Diablo.jpg"),
      require("../images/catalog/variant-razmeshcheniya(32).jpg"),
    ],
  },
  {
    id: "814",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Disette Basi",
    interiors: [
      require("../images/catalog/Disette-Basi-v-interere-1.jpg"),
      require("../images/catalog/Disette-Basi-v-interere-2.jpg"),
      require("../images/catalog/Disette-Basi-v-interere-3.jpg"),
      require("../images/catalog/Disette-Basi-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/Disette-Basi.jpg"),
      require("../images/catalog/variant-razmeshcheniya(33).jpg"),
    ],
  },
  {
    id: "815",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Dorato",
    interiors: [
      require("../images/catalog/Dorato-v-intereere-1.jpg"),
      require("../images/catalog/Dorato-v-intereere-2.jpg"),
      require("../images/catalog/Dorato-v-intereere-3.jpg"),
      require("../images/catalog/Dorato-v-intereere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/Dorato.jpg"),
      require("../images/catalog/variant-razmeshcheniya(34).jpg"),
    ],
  },
  {
    id: "816",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Michelangelo",
    interiors: [
      require("../images/catalog/Michelangelo-v-interere-1.jpg"),
      require("../images/catalog/Michelangelo-v-interere-2.jpg"),
      require("../images/catalog/Michelangelo-v-interere-3.jpg"),
      require("../images/catalog/Michelangelo-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/Michelangelo.jpg"),
      require("../images/catalog/variant-razmeshcheniya(35).jpg"),
    ],
  },
  {
    id: "817",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Nuvolato",
    interiors: [
      require("../images/catalog/Nuvolato-v-interere-1.jpg"),
      require("../images/catalog/Nuvolato-v-interere-2.jpg"),
      require("../images/catalog/Nuvolato-v-interere-3.jpg"),
      require("../images/catalog/Nuvolato-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/Nuvolato.jpg"),
      require("../images/catalog/variant-razmeshcheniya(36).jpg"),
    ],
  },
  {
    id: "818",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Palissandro Blue Ocean",
    interiors: [
      require("../images/catalog/Palissandro-Blue-Ocean-v-interere-1.png"),
      require("../images/catalog/Palissandro-Blue-Ocean-v-interere-2.png"),
      require("../images/catalog/Palissandro-Blue-Ocean-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/Palissandro-Blue-Ocean.png"),
      require("../images/catalog/variant-razmeshcheniya(7).png"),
    ],
  },
  {
    id: "819",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Pietra Stellaria",
    interiors: [
      require("../images/catalog/Pietra-Stellaria-v-interere-1.jpg"),
      require("../images/catalog/Pietra-Stellaria-v-interere-2.jpg"),
      require("../images/catalog/Pietra-Stellaria-v-interere-3.jpg"),
      require("../images/catalog/Pietra-Stellaria-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/Pietra-Stellaria.jpg"),
      require("../images/catalog/variant-razmeshcheniya(37).jpg"),
    ],
  },
  {
    id: "820",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Porto Santo",
    interiors: [
      require("../images/catalog/Porto-Santo-v-interere-1.jpg"),
      require("../images/catalog/Porto-Santo-v-interere-2.jpg"),
      require("../images/catalog/Porto-Santo-v-interere-3.jpg"),
      require("../images/catalog/Porto-Santo-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/Porto-Santo.jpg"),
      require("../images/catalog/variant-razmeshcheniya(38).jpg"),
    ],
  },
  {
    id: "821",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Rojo Alicante",
    interiors: [
      require("../images/catalog/Rojo-Alicante-v-interere-1.png"),
      require("../images/catalog/Rojo-Alicante-v-interere-2.png"),
      require("../images/catalog/Rojo-Alicante-v-interere-3.png"),
      require("../images/catalog/Rojo-Alicante-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/Rojo-Alicante.png"),
      require("../images/catalog/variant-razmeshcheniya(2).png"),
    ],
  },
  {
    id: "822",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Rosso Verona",
    interiors: [
      require("../images/catalog/Rosso-Verona-v-interere-1.png"),
      require("../images/catalog/Rosso-Verona-v-interere-2.png"),
      require("../images/catalog/Rosso-Verona-v-interere-3.png"),
      require("../images/catalog/Rosso-Verona-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/Rosso-Verona.png"),
      require("../images/catalog/variant-razmeshcheniya(3).png"),
    ],
  },
  {
    id: "823",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Sainte Anne",
    interiors: [
      require("../images/catalog/Sainte-Anne-v-interere-1.jpg"),
      require("../images/catalog/Sainte-Anne-v-interere-2.jpg"),
      require("../images/catalog/Sainte-Anne-v-interere-3.jpg"),
      require("../images/catalog/Sainte-Anne-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/Sainte-Anne.jpg"),
      require("../images/catalog/variant-razmeshcheniya(39).jpg"),
    ],
  },
  {
    id: "824",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Sandy Grey",
    interiors: [
      require("../images/catalog/Sandy-Grey-v-interere-1.png"),
      require("../images/catalog/Sandy-Grey-v-interere-2.png"),
      require("../images/catalog/Sandy-Grey-v-interere-3.png"),
      require("../images/catalog/Sandy-Grey-v-interere-4.png"),
    ],
    tovars: [
      require("../images/catalog/Sandy-Grey.png"),
      require("../images/catalog/variant-razmeshcheniya(6).png"),
    ],
  },
  {
    id: "825",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Tobaco",
    interiors: [
      require("../images/catalog/Tobaco-v-interere-1.jpg"),
      require("../images/catalog/Tobaco-v-interere-2.jpg"),
      require("../images/catalog/Tobaco-v-interere-3.jpg"),
      require("../images/catalog/Tobaco-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/Tobaco.jpg"),
      require("../images/catalog/variant-razmeshcheniya(40).jpg"),
    ],
  },
  {
    id: "826",
    Сountry: "Россия",
    Name: "Elite",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Verde Antico",
    interiors: [
      require("../images/catalog/Verde-Antico-v-interere-1.jpg"),
      require("../images/catalog/Verde-Antico-v-interere-2.jpg"),
      require("../images/catalog/Verde-Antico-v-interere-3.jpg"),
      require("../images/catalog/Verde-Antico-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/variant-razmeshcheniya(41).jpg"),
      require("../images/catalog/Verde-Antico.jpg"),
    ],
  },
];
