const initialCards = [
  {
    id: "860",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Авантюрин",

    interiors: [
      require("../images/catalog/GK_VIP/Авантюрин/interiors/avantyurin-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Авантюрин/interiors/avantyurin-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Авантюрин/interiors/avantyurin-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Авантюрин/interiors/avantyurin-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Авантюрин/tovars/avantyurin-1.jpg"),
      require("../images/catalog/GK_VIP/Авантюрин/tovars/avantyurin-2.jpg"),
      require("../images/catalog/GK_VIP/Авантюрин/tovars/avantyurin-3.jpg"),
      require("../images/catalog/GK_VIP/Авантюрин/tovars/avantyurin-4.jpg"),
      require("../images/catalog/GK_VIP/Авантюрин/tovars/avantyurin.jpg"),
    ],
  },
  {
    id: "861",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Аквамарин",

    interiors: [
      require("../images/catalog/GK_VIP/Аквамарин/interiors/akvamarin-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Аквамарин/interiors/akvamarin-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Аквамарин/interiors/akvamarin-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Аквамарин/interiors/akvamarin-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Аквамарин/tovars/akvamarin-1.jpg"),
      require("../images/catalog/GK_VIP/Аквамарин/tovars/akvamarin-2.jpg"),
      require("../images/catalog/GK_VIP/Аквамарин/tovars/akvamarin-3.jpg"),
      require("../images/catalog/GK_VIP/Аквамарин/tovars/akvamarin-4.jpg"),
      require("../images/catalog/GK_VIP/Аквамарин/tovars/akvamarin.jpg"),
    ],
  },
  {
    id: "862",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Алмаз",

    interiors: [
      require("../images/catalog/GK_VIP/Алмаз/interiors/almaz-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Алмаз/interiors/almaz-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Алмаз/interiors/almaz-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Алмаз/interiors/almaz-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Алмаз/tovars/almaz-1.jpg"),
      require("../images/catalog/GK_VIP/Алмаз/tovars/almaz-2.jpg"),
      require("../images/catalog/GK_VIP/Алмаз/tovars/almaz-3.jpg"),
      require("../images/catalog/GK_VIP/Алмаз/tovars/almaz-4.jpg"),
      require("../images/catalog/GK_VIP/Алмаз/tovars/almaz.jpg"),
    ],
  },
  {
    id: "863",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Альмандин",

    interiors: [
      require("../images/catalog/GK_VIP/Альмандин/interiors/almandin-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Альмандин/interiors/almandin-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Альмандин/interiors/almandin-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Альмандин/interiors/almandin-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Альмандин/tovars/almandin-1.jpg"),
      require("../images/catalog/GK_VIP/Альмандин/tovars/almandin-2.jpg"),
      require("../images/catalog/GK_VIP/Альмандин/tovars/almandin-3.jpeg"),
      require("../images/catalog/GK_VIP/Альмандин/tovars/almandin-4.jpg"),
      require("../images/catalog/GK_VIP/Альмандин/tovars/almandin.jpg"),
    ],
  },
  {
    id: "864",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Аметист",

    interiors: [
      require("../images/catalog/GK_VIP/Аметист/interiors/ametist-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Аметист/interiors/ametist-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Аметист/interiors/ametist-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Аметист/interiors/ametist-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Аметист/tovars/ametist-1.jpg"),
      require("../images/catalog/GK_VIP/Аметист/tovars/ametist-2.jpg"),
      require("../images/catalog/GK_VIP/Аметист/tovars/ametist-3.jpg"),
      require("../images/catalog/GK_VIP/Аметист/tovars/ametist-4.jpg"),
      require("../images/catalog/GK_VIP/Аметист/tovars/ametist.jpg"),
    ],
  },
  {
    id: "865",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Апатит",

    interiors: [
      require("../images/catalog/GK_VIP/Апатит/interiors/apatit-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Апатит/interiors/apatit-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Апатит/interiors/apatit-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Апатит/interiors/apatit-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Апатит/tovars/apatit-1.jpg"),
      require("../images/catalog/GK_VIP/Апатит/tovars/apatit-2.jpg"),
      require("../images/catalog/GK_VIP/Апатит/tovars/apatit-3.jpg"),
      require("../images/catalog/GK_VIP/Апатит/tovars/apatit-4.jpg"),
      require("../images/catalog/GK_VIP/Апатит/tovars/apatit.jpg"),
    ],
  },
  {
    id: "866",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Верделит",

    interiors: [
      require("../images/catalog/GK_VIP/Верделит/interiors/verdelit-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Верделит/interiors/verdelit-v-interere-2(1).jpg"),
      require("../images/catalog/GK_VIP/Верделит/interiors/verdelit-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Верделит/interiors/verdelit-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Верделит/tovars/verdelit-1.jpg"),
      require("../images/catalog/GK_VIP/Верделит/tovars/verdelit-2.jpg"),
      require("../images/catalog/GK_VIP/Верделит/tovars/verdelit-3.jpg"),
      require("../images/catalog/GK_VIP/Верделит/tovars/verdelit-4.jpg"),
      require("../images/catalog/GK_VIP/Верделит/tovars/verdelit.jpg"),
    ],
  },
  {
    id: "867",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Волокас",

    interiors: [
      require("../images/catalog/GK_VIP/Волокас/interiors/volokas-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Волокас/interiors/volokas-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Волокас/interiors/volokas-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Волокас/interiors/volokas-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Волокас/tovars/variant-razmeshcheniya(14).jpg"),
      require("../images/catalog/GK_VIP/Волокас/tovars/volokas.jpg"),
    ],
  },
  {
    id: "868",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Гелиодор",

    interiors: [
      require("../images/catalog/GK_VIP/Гелиодор/interiors/geliodor-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Гелиодор/interiors/geliodor-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Гелиодор/interiors/geliodor-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Гелиодор/interiors/geliodor-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Гелиодор/tovars/geliodor-1.jpg"),
      require("../images/catalog/GK_VIP/Гелиодор/tovars/geliodor-2.jpg"),
      require("../images/catalog/GK_VIP/Гелиодор/tovars/geliodor-3.jpg"),
      require("../images/catalog/GK_VIP/Гелиодор/tovars/geliodor-4.jpg"),
      require("../images/catalog/GK_VIP/Гелиодор/tovars/geliodor.jpg"),
    ],
  },
  {
    id: "869",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Гессонит",

    interiors: [
      require("../images/catalog/GK_VIP/Гессонит/interiors/gessonit-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Гессонит/interiors/gessonit-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Гессонит/interiors/gessonit-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Гессонит/interiors/gessonit-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Гессонит/tovars/gessonit-1.jpg"),
      require("../images/catalog/GK_VIP/Гессонит/tovars/gessonit-2.jpg"),
      require("../images/catalog/GK_VIP/Гессонит/tovars/gessonit-3.jpg"),
      require("../images/catalog/GK_VIP/Гессонит/tovars/gessonit-4.jpg"),
      require("../images/catalog/GK_VIP/Гессонит/tovars/gessonit.jpg"),
    ],
  },
  {
    id: "870",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Гранат",

    interiors: [
      require("../images/catalog/GK_VIP/Гранат/interiors/granat-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Гранат/interiors/granat-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Гранат/interiors/granat-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Гранат/interiors/granat-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Гранат/tovars/granat-1.jpg"),
      require("../images/catalog/GK_VIP/Гранат/tovars/granat-2.jpg"),
      require("../images/catalog/GK_VIP/Гранат/tovars/granat-3.jpg"),
      require("../images/catalog/GK_VIP/Гранат/tovars/granat-4.jpg"),
      require("../images/catalog/GK_VIP/Гранат/tovars/granat.jpg"),
    ],
  },
  {
    id: "871",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Доломит",

    interiors: [
      require("../images/catalog/GK_VIP/Доломит/interiors/dolomit-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Доломит/interiors/dolomit-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Доломит/interiors/dolomit-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Доломит/interiors/dolomit-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Доломит/tovars/dolomit(1).jpg"),
      require("../images/catalog/GK_VIP/Доломит/tovars/dolomit.jpg"),
    ],
  },
  {
    id: "872",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Дымчатый кварц",

    interiors: [
      require("../images/catalog/GK_VIP/Дымчатый кварц/interiors/dimchatiy-kvarts-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Дымчатый кварц/interiors/dimchatiy-kvarts-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Дымчатый кварц/interiors/dimchatiy-kvarts-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Дымчатый кварц/interiors/dimchatiy-kvarts-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Дымчатый кварц/tovars/dimchatiy-kvarts-1.jpg"),
      require("../images/catalog/GK_VIP/Дымчатый кварц/tovars/dimchatiy-kvarts-2.jpg"),
      require("../images/catalog/GK_VIP/Дымчатый кварц/tovars/dimchatiy-kvarts-3.jpg"),
      require("../images/catalog/GK_VIP/Дымчатый кварц/tovars/dimchatiy-kvarts-4.jpg"),
      require("../images/catalog/GK_VIP/Дымчатый кварц/tovars/dimchatiy-kvarts.jpg"),
    ],
  },
  {
    id: "873",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Имперадор",

    interiors: [
      require("../images/catalog/GK_VIP/Имперадор/interiors/imperador-v-interere-1.jpeg"),
      require("../images/catalog/GK_VIP/Имперадор/interiors/imperador-v-interere-2.jpeg"),
      require("../images/catalog/GK_VIP/Имперадор/interiors/imperador-v-interere-3.jpeg"),
      require("../images/catalog/GK_VIP/Имперадор/interiors/imperador-v-interere-4.jpeg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Имперадор/tovars/imperador.jpeg"),
      require("../images/catalog/GK_VIP/Имперадор/tovars/imperator.jpg"),
    ],
  },
  {
    id: "874",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Лазурит",

    interiors: [
      require("../images/catalog/GK_VIP/Лазурит/interiors/lazurit-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Лазурит/interiors/lazurit-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Лазурит/interiors/lazurit-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Лазурит/interiors/lazurit-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Лазурит/tovars/lazurit-1.jpg"),
      require("../images/catalog/GK_VIP/Лазурит/tovars/lazurit-2.jpg"),
      require("../images/catalog/GK_VIP/Лазурит/tovars/lazurit-3.jpg"),
      require("../images/catalog/GK_VIP/Лазурит/tovars/lazurit-4.jpg"),
      require("../images/catalog/GK_VIP/Лазурит/tovars/lazurit.jpg"),
    ],
  },
  {
    id: "875",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Малахит",

    interiors: [
      require("../images/catalog/GK_VIP/Малахит/interiors/malahit-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Малахит/interiors/malahit-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Малахит/interiors/malahit-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Малахит/interiors/malahit-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Малахит/tovars/malahit-1.jpg"),
      require("../images/catalog/GK_VIP/Малахит/tovars/malahit-2.jpg"),
      require("../images/catalog/GK_VIP/Малахит/tovars/malahit-3.jpg"),
      require("../images/catalog/GK_VIP/Малахит/tovars/malahit-4.jpg"),
      require("../images/catalog/GK_VIP/Малахит/tovars/malahit.jpg"),
    ],
  },
  {
    id: "876",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Неро",

    interiors: [
      require("../images/catalog/GK_VIP/Неро/interiors/nero-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Неро/interiors/nero-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Неро/interiors/nero-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Неро/interiors/nero-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Неро/tovars/nero.jpg"),
      require("../images/catalog/GK_VIP/Неро/tovars/variant-razmeshcheniya(26).jpg"),
    ],
  },
  {
    id: "877",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Нефрит",

    interiors: [
      require("../images/catalog/GK_VIP/Нефрит/interiors/nefrit-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Нефрит/interiors/nefrit-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Нефрит/interiors/nefrit-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Нефрит/interiors/nefrit-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Нефрит/tovars/nefrit-1.jpg"),
      require("../images/catalog/GK_VIP/Нефрит/tovars/nefrit-2.jpg"),
      require("../images/catalog/GK_VIP/Нефрит/tovars/nefrit-3.jpg"),
      require("../images/catalog/GK_VIP/Нефрит/tovars/nefrit-4.jpg"),
      require("../images/catalog/GK_VIP/Нефрит/tovars/nefrit.jpg"),
    ],
  },
  {
    id: "878",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Оникс",

    interiors: [
      require("../images/catalog/GK_VIP/Оникс/interiors/oniks-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Оникс/interiors/oniks-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Оникс/interiors/oniks-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Оникс/interiors/oniks-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Оникс/tovars/oniks-1.jpg"),
      require("../images/catalog/GK_VIP/Оникс/tovars/oniks-2.jpg"),
      require("../images/catalog/GK_VIP/Оникс/tovars/oniks-3.jpg"),
      require("../images/catalog/GK_VIP/Оникс/tovars/oniks-4.jpg"),
      require("../images/catalog/GK_VIP/Оникс/tovars/oniks.jpg"),
    ],
  },
  {
    id: "879",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Перламутр",

    interiors: [
      require("../images/catalog/GK_VIP/Перламутр/interiors/perlamutr-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Перламутр/interiors/perlamutr-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Перламутр/interiors/perlamutr-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Перламутр/interiors/perlamutr-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Перламутр/tovars/perlamutr-1.jpg"),
      require("../images/catalog/GK_VIP/Перламутр/tovars/perlamutr-2.jpg"),
      require("../images/catalog/GK_VIP/Перламутр/tovars/perlamutr-3.jpg"),
      require("../images/catalog/GK_VIP/Перламутр/tovars/perlamutr-4.jpg"),
      require("../images/catalog/GK_VIP/Перламутр/tovars/perlamutr.jpg"),
    ],
  },
  {
    id: "880",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Сапфир",

    interiors: [
      require("../images/catalog/GK_VIP/Сапфир/interiors/sapfir-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Сапфир/interiors/sapfir-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Сапфир/interiors/sapfir-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Сапфир/interiors/sapfir-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Сапфир/tovars/sapfir-1.jpg"),
      require("../images/catalog/GK_VIP/Сапфир/tovars/sapfir-2.jpg"),
      require("../images/catalog/GK_VIP/Сапфир/tovars/sapfir-3.jpg"),
      require("../images/catalog/GK_VIP/Сапфир/tovars/sapfir-4.jpg"),
      require("../images/catalog/GK_VIP/Сапфир/tovars/sapfir.jpg"),
    ],
  },
  {
    id: "881",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Сердолик",

    interiors: [
      require("../images/catalog/GK_VIP/Сердолик/interiors/serdolik-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Сердолик/interiors/serdolik-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Сердолик/interiors/serdolik-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Сердолик/interiors/serdolik-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Сердолик/tovars/serdolik-1.jpg"),
      require("../images/catalog/GK_VIP/Сердолик/tovars/serdolik-2.jpg"),
      require("../images/catalog/GK_VIP/Сердолик/tovars/serdolik-3.jpg"),
      require("../images/catalog/GK_VIP/Сердолик/tovars/serdolik-4.jpg"),
      require("../images/catalog/GK_VIP/Сердолик/tovars/serdolik.jpg"),
    ],
  },
  {
    id: "882",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Танзанит",

    interiors: [
      require("../images/catalog/GK_VIP/Танзанит/interiors/tanzanit-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Танзанит/interiors/tanzanit-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Танзанит/interiors/tanzanit-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Танзанит/interiors/tanzanit-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Танзанит/tovars/tanzanit-1.jpg"),
      require("../images/catalog/GK_VIP/Танзанит/tovars/tanzanit-2.jpg"),
      require("../images/catalog/GK_VIP/Танзанит/tovars/tanzanit-3.jpg"),
      require("../images/catalog/GK_VIP/Танзанит/tovars/tanzanit-4.jpg"),
      require("../images/catalog/GK_VIP/Танзанит/tovars/tanzanit.jpg"),
    ],
  },
  {
    id: "883",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Хризолит",

    interiors: [
      require("../images/catalog/GK_VIP/Хризолит/interiors/hrizolit-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Хризолит/interiors/hrizolit-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Хризолит/interiors/hrizolit-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Хризолит/interiors/hrizolit-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Хризолит/tovars/hrizolit-1.jpg"),
      require("../images/catalog/GK_VIP/Хризолит/tovars/hrizolit-2.jpg"),
      require("../images/catalog/GK_VIP/Хризолит/tovars/hrizolit-3.jpg"),
      require("../images/catalog/GK_VIP/Хризолит/tovars/hrizolit-4.jpg"),
      require("../images/catalog/GK_VIP/Хризолит/tovars/hrizolit.jpg"),
    ],
  },
  {
    id: "884",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Цитрин",

    interiors: [
      require("../images/catalog/GK_VIP/Цитрин/interiors/tsitrin-v-interere-1.jpg"),
      require("../images/catalog/GK_VIP/Цитрин/interiors/tsitrin-v-interere-2.jpg"),
      require("../images/catalog/GK_VIP/Цитрин/interiors/tsitrin-v-interere-3.jpg"),
      require("../images/catalog/GK_VIP/Цитрин/interiors/tsitrin-v-interere-4.jpg"),
    ],
    tovars: [
      require("../images/catalog/GK_VIP/Цитрин/tovars/tsitrin-1.jpg"),
      require("../images/catalog/GK_VIP/Цитрин/tovars/tsitrin-2.jpg"),
      require("../images/catalog/GK_VIP/Цитрин/tovars/tsitrin-3.jpg"),
      require("../images/catalog/GK_VIP/Цитрин/tovars/tsitrin-4.jpg"),
      require("../images/catalog/GK_VIP/Цитрин/tovars/tsitrin.jpg"),
    ],
  },
];
