const initialCards = [
  {
    id: "860",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Авантюрин",

    interiors: [
      require("avantyurin-v-interere-1.jpg"),
      require("avantyurin-v-interere-2.jpg"),
      require("avantyurin-v-interere-3.jpg"),
      require("avantyurin-v-interere-4.jpg"),
    ],
    tovars: [
      require("avantyurin-1.jpg"),
      require("avantyurin-2.jpg"),
      require("avantyurin-3.jpg"),
      require("avantyurin-4.jpg"),
      require("avantyurin.jpg"),
    ],
  },
  {
    id: "861",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Аквамарин",

    interiors: [
      require("akvamarin-v-interere-1.jpg"),
      require("akvamarin-v-interere-2.jpg"),
      require("akvamarin-v-interere-3.jpg"),
      require("akvamarin-v-interere-4.jpg"),
    ],
    tovars: [
      require("akvamarin-1.jpg"),
      require("akvamarin-2.jpg"),
      require("akvamarin-3.jpg"),
      require("akvamarin-4.jpg"),
      require("akvamarin.jpg"),
    ],
  },
  {
    id: "862",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Алмаз",

    interiors: [
      require("almaz-v-interere-1.jpg"),
      require("almaz-v-interere-2.jpg"),
      require("almaz-v-interere-3.jpg"),
      require("almaz-v-interere-4.jpg"),
    ],
    tovars: [
      require("almaz-1.jpg"),
      require("almaz-2.jpg"),
      require("almaz-3.jpg"),
      require("almaz-4.jpg"),
      require("almaz.jpg"),
    ],
  },
  {
    id: "863",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Альмандин",

    interiors: [
      require("almandin-v-interere-1.jpg"),
      require("almandin-v-interere-2.jpg"),
      require("almandin-v-interere-3.jpg"),
      require("almandin-v-interere-4.jpg"),
    ],
    tovars: [
      require("almandin-1.jpg"),
      require("almandin-2.jpg"),
      require("almandin-3.jpeg"),
      require("almandin-4.jpg"),
      require("almandin.jpg"),
    ],
  },
  {
    id: "864",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Аметист",

    interiors: [
      require("ametist-v-interere-1.jpg"),
      require("ametist-v-interere-2.jpg"),
      require("ametist-v-interere-3.jpg"),
      require("ametist-v-interere-4.jpg"),
    ],
    tovars: [
      require("ametist-1.jpg"),
      require("ametist-2.jpg"),
      require("ametist-3.jpg"),
      require("ametist-4.jpg"),
      require("ametist.jpg"),
    ],
  },
  {
    id: "865",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Апатит",

    interiors: [
      require("apatit-v-interere-1.jpg"),
      require("apatit-v-interere-2.jpg"),
      require("apatit-v-interere-3.jpg"),
      require("apatit-v-interere-4.jpg"),
    ],
    tovars: [
      require("apatit-1.jpg"),
      require("apatit-2.jpg"),
      require("apatit-3.jpg"),
      require("apatit-4.jpg"),
      require("apatit.jpg"),
    ],
  },
  {
    id: "866",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Верделит",

    interiors: [
      require("verdelit-v-interere-1.jpg"),
      require("verdelit-v-interere-2(1).jpg"),
      require("verdelit-v-interere-3.jpg"),
      require("verdelit-v-interere-4.jpg"),
    ],
    tovars: [
      require("verdelit-1.jpg"),
      require("verdelit-2.jpg"),
      require("verdelit-3.jpg"),
      require("verdelit-4.jpg"),
      require("verdelit.jpg"),
    ],
  },
  {
    id: "867",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Волокас",

    interiors: [
      require("volokas-v-interere-1.jpg"),
      require("volokas-v-interere-2.jpg"),
      require("volokas-v-interere-3.jpg"),
      require("volokas-v-interere-4.jpg"),
    ],
    tovars: [require("variant-razmeshcheniya(14).jpg"), require("volokas.jpg")],
  },
  {
    id: "868",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Гелиодор",

    interiors: [
      require("geliodor-v-interere-1.jpg"),
      require("geliodor-v-interere-2.jpg"),
      require("geliodor-v-interere-3.jpg"),
      require("geliodor-v-interere-4.jpg"),
    ],
    tovars: [
      require("geliodor-1.jpg"),
      require("geliodor-2.jpg"),
      require("geliodor-3.jpg"),
      require("geliodor-4.jpg"),
      require("geliodor.jpg"),
    ],
  },
  {
    id: "869",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Гессонит",

    interiors: [
      require("gessonit-v-interere-1.jpg"),
      require("gessonit-v-interere-2.jpg"),
      require("gessonit-v-interere-3.jpg"),
      require("gessonit-v-interere-4.jpg"),
    ],
    tovars: [
      require("gessonit-1.jpg"),
      require("gessonit-2.jpg"),
      require("gessonit-3.jpg"),
      require("gessonit-4.jpg"),
      require("gessonit.jpg"),
    ],
  },
  {
    id: "870",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Гранат",

    interiors: [
      require("granat-v-interere-1.jpg"),
      require("granat-v-interere-2.jpg"),
      require("granat-v-interere-3.jpg"),
      require("granat-v-interere-4.jpg"),
    ],
    tovars: [
      require("granat-1.jpg"),
      require("granat-2.jpg"),
      require("granat-3.jpg"),
      require("granat-4.jpg"),
      require("granat.jpg"),
    ],
  },
  {
    id: "871",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Доломит",

    interiors: [
      require("dolomit-v-interere-1.jpg"),
      require("dolomit-v-interere-2.jpg"),
      require("dolomit-v-interere-3.jpg"),
      require("dolomit-v-interere-4.jpg"),
    ],
    tovars: [require("dolomit(1).jpg"), require("dolomit.jpg")],
  },
  {
    id: "872",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Дымчатый кварц",

    interiors: [
      require("dimchatiy-kvarts-v-interere-1.jpg"),
      require("dimchatiy-kvarts-v-interere-2.jpg"),
      require("dimchatiy-kvarts-v-interere-3.jpg"),
      require("dimchatiy-kvarts-v-interere-4.jpg"),
    ],
    tovars: [
      require("dimchatiy-kvarts-1.jpg"),
      require("dimchatiy-kvarts-2.jpg"),
      require("dimchatiy-kvarts-3.jpg"),
      require("dimchatiy-kvarts-4.jpg"),
      require("dimchatiy-kvarts.jpg"),
    ],
  },
  {
    id: "873",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Имперадор",

    interiors: [
      require("imperador-v-interere-1.jpeg"),
      require("imperador-v-interere-2.jpeg"),
      require("imperador-v-interere-3.jpeg"),
      require("imperador-v-interere-4.jpeg"),
    ],
    tovars: [require("imperador.jpeg"), require("imperator.jpg")],
  },
  {
    id: "874",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Лазурит",

    interiors: [
      require("lazurit-v-interere-1.jpg"),
      require("lazurit-v-interere-2.jpg"),
      require("lazurit-v-interere-3.jpg"),
      require("lazurit-v-interere-4.jpg"),
    ],
    tovars: [
      require("lazurit-1.jpg"),
      require("lazurit-2.jpg"),
      require("lazurit-3.jpg"),
      require("lazurit-4.jpg"),
      require("lazurit.jpg"),
    ],
  },
  {
    id: "875",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Малахит",

    interiors: [
      require("malahit-v-interere-1.jpg"),
      require("malahit-v-interere-2.jpg"),
      require("malahit-v-interere-3.jpg"),
      require("malahit-v-interere-4.jpg"),
    ],
    tovars: [
      require("malahit-1.jpg"),
      require("malahit-2.jpg"),
      require("malahit-3.jpg"),
      require("malahit-4.jpg"),
      require("malahit.jpg"),
    ],
  },
  {
    id: "876",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Неро",

    interiors: [
      require("nero-v-interere-1.jpg"),
      require("nero-v-interere-2.jpg"),
      require("nero-v-interere-3.jpg"),
      require("nero-v-interere-4.jpg"),
    ],
    tovars: [require("nero.jpg"), require("variant-razmeshcheniya(26).jpg")],
  },
  {
    id: "877",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Нефрит",

    interiors: [
      require("nefrit-v-interere-1.jpg"),
      require("nefrit-v-interere-2.jpg"),
      require("nefrit-v-interere-3.jpg"),
      require("nefrit-v-interere-4.jpg"),
    ],
    tovars: [
      require("nefrit-1.jpg"),
      require("nefrit-2.jpg"),
      require("nefrit-3.jpg"),
      require("nefrit-4.jpg"),
      require("nefrit.jpg"),
    ],
  },
  {
    id: "878",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Оникс",

    interiors: [
      require("oniks-v-interere-1.jpg"),
      require("oniks-v-interere-2.jpg"),
      require("oniks-v-interere-3.jpg"),
      require("oniks-v-interere-4.jpg"),
    ],
    tovars: [
      require("oniks-1.jpg"),
      require("oniks-2.jpg"),
      require("oniks-3.jpg"),
      require("oniks-4.jpg"),
      require("oniks.jpg"),
    ],
  },
  {
    id: "879",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Перламутр",

    interiors: [
      require("perlamutr-v-interere-1.jpg"),
      require("perlamutr-v-interere-2.jpg"),
      require("perlamutr-v-interere-3.jpg"),
      require("perlamutr-v-interere-4.jpg"),
    ],
    tovars: [
      require("perlamutr-1.jpg"),
      require("perlamutr-2.jpg"),
      require("perlamutr-3.jpg"),
      require("perlamutr-4.jpg"),
      require("perlamutr.jpg"),
    ],
  },
  {
    id: "880",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Сапфир",

    interiors: [
      require("sapfir-v-interere-1.jpg"),
      require("sapfir-v-interere-2.jpg"),
      require("sapfir-v-interere-3.jpg"),
      require("sapfir-v-interere-4.jpg"),
    ],
    tovars: [
      require("sapfir-1.jpg"),
      require("sapfir-2.jpg"),
      require("sapfir-3.jpg"),
      require("sapfir-4.jpg"),
      require("sapfir.jpg"),
    ],
  },
  {
    id: "881",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Сердолик",

    interiors: [
      require("serdolik-v-interere-1.jpg"),
      require("serdolik-v-interere-2.jpg"),
      require("serdolik-v-interere-3.jpg"),
      require("serdolik-v-interere-4.jpg"),
    ],
    tovars: [
      require("serdolik-1.jpg"),
      require("serdolik-2.jpg"),
      require("serdolik-3.jpg"),
      require("serdolik-4.jpg"),
      require("serdolik.jpg"),
    ],
  },
  {
    id: "882",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Танзанит",

    interiors: [
      require("tanzanit-v-interere-1.jpg"),
      require("tanzanit-v-interere-2.jpg"),
      require("tanzanit-v-interere-3.jpg"),
      require("tanzanit-v-interere-4.jpg"),
    ],
    tovars: [
      require("tanzanit-1.jpg"),
      require("tanzanit-2.jpg"),
      require("tanzanit-3.jpg"),
      require("tanzanit-4.jpg"),
      require("tanzanit.jpg"),
    ],
  },
  {
    id: "883",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Хризолит",

    interiors: [
      require("hrizolit-v-interere-1.jpg"),
      require("hrizolit-v-interere-2.jpg"),
      require("hrizolit-v-interere-3.jpg"),
      require("hrizolit-v-interere-4.jpg"),
    ],
    tovars: [
      require("hrizolit-1.jpg"),
      require("hrizolit-2.jpg"),
      require("hrizolit-3.jpg"),
      require("hrizolit-4.jpg"),
      require("hrizolit.jpg"),
    ],
  },
  {
    id: "884",
    Сountry: "Россия",
    Name: "VIP",
    Category: "GibkyMramor",
    Size: "120x240",
    Collection: "Цитрин",

    interiors: [
      require("tsitrin-v-interere-1.jpg"),
      require("tsitrin-v-interere-2.jpg"),
      require("tsitrin-v-interere-3.jpg"),
      require("tsitrin-v-interere-4.jpg"),
    ],
    tovars: [
      require("tsitrin-1.jpg"),
      require("tsitrin-2.jpg"),
      require("tsitrin-3.jpg"),
      require("tsitrin-4.jpg"),
      require("tsitrin.jpg"),
    ],
  },
];
